config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :candidates do
    #  自定義路徑
    # member/collectio do
    #   post/get(方法) :名稱
    # end

    member do
      post :vote
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  validates :name, presence: true
  has_many :vote_logs
end

app/models/vote_log.rb
class VoteLog < ApplicationRecord
  belongs_to :candidate, counter_cache: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController

  before_action :find_candidate, only:  [ :show, :edit, :update, :destroy, :vote]
  # before_action :find_candidate, :except [ :index, :create, :new]

  def index
    @candidate = Candidate.all
  end

  def show
  end

  def new
    @candidate = Candidate.new
  end

  def create
    @candidate = Candidate.new(candidate_params)
    if @candidate.save
      redirect_to '/candidates', notice: 'Candidate created!'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @candidate.update(candidate_params)
      redirect_to '/candidates', notice: 'Candidate updated!'
    else
      render :edit
    end
  end

  def destroy
    @candidate.destroy
    redirect_to '/candidates', notice: 'Candidate deleted!'
  end

  def vote
    # VoteLog.create(candidate: @candidate, ip_address: request.remote_ip)
    @candidate.vote_logs.create(ip_address: request.remote_ip)

    # send mail
    # VoteMailer.vote_notify('z123456618@hotmail.com').deliver

    redirect_to '/candidates', notice: 'Voted!'
  end

  private
  def candidate_params
    params.require(:candidate).permit(:name, :party, :age, :politics)
  end

  def find_candidate
    @candidate = Candidate.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/candidates/_form.erb
<!--  判斷是否有錯誤訊息-->
<% if @candidate.errors.any? %>
  <ul>
    <!--印出錯誤訊息-->
    <% @candidate.errors.full_messages.each do |messages| %>
      <li><%= messages %>></li>
    <% end %>
  </ul>
<% end %>


<%= form_for(@candidate) do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :party %>
    <%= form.text_field :party %>
  </div>

  <div>
    <%= form.label :age %>
    <%= form.text_field :age %>
  </div>

  <div>
    <%= form.label :politics %>
    <%= form.text_area :politics %>
  </div>
  <%= form.submit %>
<% end %>
</div>

app/views/candidates/edit.erb
<h1>Edit Candidate</h1>
<%= render 'form', candidate: @candidate %>

app/views/candidates/index.html.erb

    <meta charset="UTF-8">


  <div>
    <!-- 暫存提示 -->

  </div>
  <!--  鏈接 => 創建候選人-->
  <!--  <%#= link_to 'Add Candidates', '/candidates/new' %>  <a href=" /candidates/new">Add Candidates</a> -->
  <h1> <%= link_to 'Add Candidates',  new_candidate_path %></h1>

  <!-- 候選人表格 -->
  <table>
    <tr>
      <td></td>
      <td>Vote</td>
      <td>Name</td>
      <td>Party</td>
      <td>Age</td>
      <td>Action</td>
    </tr>

  <!--  以each(遍歷)方式，印出資料-->
    <% @candidate.each do |candidate|  %>
      <tr>
        <td><%= link_to 'vote',  vote_candidate_url(candidate.id),method: 'post' %></td>
        <td><%= candidate.vote_logs.size %></td>
        <td><%= link_to candidate.name, candidate_path(candidate.id) %></td>
        <td><%= candidate.party %>y</td>
        <td><%= candidate.age %></td>
        <!--  更新-->
        <td>
          <%= link_to 'Update',  edit_candidate_path(candidate.id) %>
          <%= link_to 'Delete',  candidate_path(candidate.id), method: 'delete', data: {confirm: 'are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </table>


app/views/candidates/new.html.erb
<h1>Add Candidate</h1>
<%= render 'form', candidate: @candidate %>

app/views/candidates/show.erb
<% if @candidate %>

  <h1><%= @candidate.name %></h1>

  <ul>
    <li>party: <%= @candidate.party %></li>
    <li>age: <%= @candidate.age %></li>
    <li>politics: <%= @candidate.politics %></li>
  </ul>

<% else %>

  <h1>No Record found!</h1>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VoteMe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= notice %>
    <%= yield %>
  </body>
</html>